"""Smart Router module for cognitive load balancing and model selection.

This module provides the SmartRouter class that analyzes task complexity and
hardware constraints to select optimal models for different tasks. It implements
a cognitive load balancing approach that maximizes the precision/inference time
ratio by routing tasks to the most appropriate models.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from typing import Any, ClassVar

from ..db_manager import DBManager
from ..hardware_discovery import HardwareInfo, discover_hardware
from ..logger import get_logger
from ..model_registry import ModelRegistry

logger = get_logger(__name__)


@dataclass
class TaskComplexityMetrics:
    """Metrics used to calculate task complexity score."""

    scope_factor: float  # Number of features impacted
    dependency_depth: int  # Number of dependencies in task graph
    resource_intensity: float  # Skill type multiplier
    file_count: int  # Number of files affected
    lines_changed: int  # Estimated lines of code changed

    @property
    def complexity_score(self) -> float:
        """Calculate overall complexity score."""
        # Weighted combination of factors
        return (
            self.scope_factor * 1.0
            + self.dependency_depth * 0.5
            + self.resource_intensity * 2.0
            + self.file_count * 0.1
            + self.lines_changed * 0.01
        )


@dataclass
class ExecutionPlan:
    """Execution plan generated by the SmartRouter."""

    model_id: str
    model_name: str
    quantization: str
    execution_mode: str  # "parallel" or "queue"
    estimated_vram_gb: float
    estimated_time_seconds: float
    reason: str


class SmartRouter:
    """Cognitive Load Balancer that routes tasks to optimal models.

    The SmartRouter analyzes task complexity and hardware constraints to
    determine the best model and execution strategy. It implements the
    "Apache of IA" philosophy by making intelligent routing decisions based
    on available resources.
    """

    # Model size thresholds (in billions of parameters)
    SMALL_MODEL_THRESHOLD = 8.0
    MEDIUM_MODEL_THRESHOLD = 13.0
    LARGE_MODEL_THRESHOLD = 70.0

    # Complexity score thresholds
    SIMPLE_TASK_THRESHOLD = 5.0
    MODERATE_TASK_THRESHOLD = 15.0

    # RAM thresholds (in GB)
    HIGH_RAM_THRESHOLD = 32
    MEDIUM_RAM_THRESHOLD = 16
    LOW_RAM_THRESHOLD = 8

    # Dependency threshold
    DEPENDENCY_THRESHOLD = 5

    # Resource intensity multipliers for different skill types
    SKILL_MULTIPLIERS: ClassVar[dict[str, float]] = {
        "general": 1.0,
        "logic": 1.2,
        "coding": 1.5,
        "vision": 2.5,
        "audio": 2.5,
        "reasoning": 2.0,
    }

    def __init__(self, model_registry: ModelRegistry | None = None) -> None:
        """Initialize the SmartRouter.

        Args:
            model_registry: Optional ModelRegistry instance. If not provided,
                           a new one will be created with a default DBManager.
        """
        if model_registry is None:
            db_manager = DBManager()
            model_registry = ModelRegistry(db_manager)
        self.model_registry = model_registry
        self._hardware_info: HardwareInfo | None = None
        self._hardware_lock = asyncio.Lock()

    async def _get_hardware_info(self) -> HardwareInfo:
        """Get hardware information with caching."""
        if self._hardware_info is None:
            async with self._hardware_lock:
                if self._hardware_info is None:
                    self._hardware_info = await discover_hardware()
        return self._hardware_info

    async def calculate_complexity(
        self,
        task_description: str,
        feature_count: int,
        dependency_count: int,
        file_count: int,
        estimated_lines: int,
        skill_type: str = "general",
    ) -> TaskComplexityMetrics:
        """Calculate task complexity metrics.

        Args:
            task_description: Description of the task
            feature_count: Number of features impacted
            dependency_count: Number of dependencies in task graph
            file_count: Number of files affected
            estimated_lines: Estimated lines of code changed
            skill_type: Type of skill required (general, vision, audio, etc.)

        Returns:
            TaskComplexityMetrics with calculated values
        """
        # Calculate scope factor based on feature count
        scope_factor = min(feature_count / 5.0, 5.0)  # Cap at 5.0

        # Calculate resource intensity based on skill type
        resource_intensity = self.SKILL_MULTIPLIERS.get(skill_type, 1.0)

        return TaskComplexityMetrics(
            scope_factor=scope_factor,
            dependency_depth=dependency_count,
            resource_intensity=resource_intensity,
            file_count=file_count,
            lines_changed=estimated_lines,
        )

    async def select_model_for_task(
        self, complexity: TaskComplexityMetrics
    ) -> tuple[str, str]:
        """Select the most appropriate model based on complexity.

        Args:
            complexity: Task complexity metrics

        Returns:
            Tuple of (model_id, quantization)
        """
        hardware = await self._get_hardware_info()
        total_ram_gb = hardware.total_ram_gb

        # Determine model size based on complexity and available RAM
        if complexity.complexity_score > self.MODERATE_TASK_THRESHOLD:
            # Complex task - use larger model
            if total_ram_gb >= self.HIGH_RAM_THRESHOLD:
                return ("meta-llama/Llama-3-70b-chat-hf", "Q4_K_M")
            if total_ram_gb >= self.MEDIUM_RAM_THRESHOLD:
                return ("meta-llama/Llama-3-8b-chat-hf", "Q8_0")
            return ("meta-llama/Llama-3-8b-chat-hf", "Q4_K_M")
        if complexity.complexity_score > self.SIMPLE_TASK_THRESHOLD:
            # Moderate task - use medium model
            if total_ram_gb >= self.MEDIUM_RAM_THRESHOLD:
                return ("meta-llama/Llama-3-8b-chat-hf", "Q8_0")
            return ("meta-llama/Llama-3-8b-chat-hf", "Q4_K_M")
        # Simple task - use small model
        return ("meta-llama/Llama-3-8b-chat-hf", "Q4_K_M")

    async def determine_execution_mode(
        self, complexity: TaskComplexityMetrics, model_id: str
    ) -> str:
        """Determine execution mode based on complexity and model.

        Args:
            complexity: Task complexity metrics
            model_id: Selected model ID

        Returns:
            Execution mode: "parallel" or "queue"
        """
        hardware = await self._get_hardware_info()
        total_ram_gb = hardware.total_ram_gb

        # Check if model requires significant resources
        is_large_model = "70b" in model_id.lower()

        # Determine execution mode
        if complexity.complexity_score < self.SIMPLE_TASK_THRESHOLD:
            return "parallel"
        if (
            is_large_model
            or total_ram_gb < self.MEDIUM_RAM_THRESHOLD
            or complexity.dependency_depth > self.DEPENDENCY_THRESHOLD
        ):
            return "queue"
        return "parallel"

    async def generate_execution_plan(
        self,
        task_description: str,
        feature_count: int = 1,
        dependency_count: int = 0,
        file_count: int = 1,
        estimated_lines: int = 100,
        skill_type: str = "general",
    ) -> ExecutionPlan:
        """Generate a complete execution plan for a task.

        Args:
            task_description: Description of the task
            feature_count: Number of features impacted
            dependency_count: Number of dependencies in task graph
            file_count: Number of files affected
            estimated_lines: Estimated lines of code changed
            skill_type: Type of skill required

        Returns:
            ExecutionPlan with model selection and execution strategy
        """
        # Calculate complexity metrics
        complexity = await self.calculate_complexity(
            task_description,
            feature_count,
            dependency_count,
            file_count,
            estimated_lines,
            skill_type,
        )

        # Select model
        model_id, quantization = await self.select_model_for_task(complexity)

        # Determine execution mode
        execution_mode = await self.determine_execution_mode(complexity, model_id)

        # Estimate VRAM requirement
        # Extract model size from model_id
        model_size = 70.0 if "70b" in model_id.lower() else 8.0
        vram_gb = model_size * 0.5  # Rough estimate: params * bits / 8 * buffer

        # Estimate execution time based on complexity
        base_time = 30.0  # Base time in seconds
        time_multiplier = complexity.complexity_score / 10.0
        estimated_time = base_time * time_multiplier

        # Get hardware info for reason
        hardware = await self._get_hardware_info()

        # Generate reason
        reason = (
            f"Complexity score: {complexity.complexity_score:.2f}, "
            f"Mode: {execution_mode}, "
            f"RAM: {hardware.total_ram_gb:.1f}GB"
        )

        return ExecutionPlan(
            model_id=model_id,
            model_name=model_id.split("/")[-1],
            quantization=quantization,
            execution_mode=execution_mode,
            estimated_vram_gb=vram_gb,
            estimated_time_seconds=estimated_time,
            reason=reason,
        )

    async def route_batch(self, tasks: list[dict[str, Any]]) -> list[ExecutionPlan]:
        """Route a batch of tasks and generate execution plans.

        Args:
            tasks: List of task descriptions with metadata

        Returns:
            List of ExecutionPlan objects
        """
        plans = []
        for task in tasks:
            plan = await self.generate_execution_plan(
                task.get("description", ""),
                feature_count=task.get("feature_count", 1),
                dependency_count=task.get("dependency_count", 0),
                file_count=task.get("file_count", 1),
                estimated_lines=task.get("estimated_lines", 100),
                skill_type=task.get("skill_type", "general"),
            )
            plans.append(plan)
        return plans
